LIBPATH=../lib
LIBS=-lxlayer -lpcap
INCL=../include

t: t.o
	gcc -o t t.o -L$(LIBPATH) $(LIBS)
t.o: t.c
	gcc -c t.c -I$(INCL)
taddr: taddr.o
	gcc -o taddr taddr.o -L$(LIBPATH) $(LIBS)
taddr.o: taddr.c
	gcc -c taddr.c -I$(INCL)
prnif: prnif.o
	gcc -o prnif prnif.o -L$(LIBPATH) $(LIBS)
prnif.o: prnif.c
	gcc -c prnif.c -I$(INCL)
tsend: tsend.o
	gcc -o tsend tsend.o -L$(LIBPATH) $(LIBS)
tsend.o: tsend.c
	gcc -c tsend.c -I$(INCL)
tsyn: tsyn.o
	gcc -o tsyn tsyn.o -L$(LIBPATH) $(LIBS)
tsyn.o: tsyn.c
	gcc -c tsyn.c -I$(INCL)
x: x.o
	gcc -o x x.o -L$(LIBPATH) $(LIBS)
x.o: x.c
	gcc -c x.c -I$(INCL)
tmenu: tmenu.o
	gcc -o tmenu tmenu.o -L$(LIBPATH) $(LIBS)
tmenu.o: tmenu.c
	gcc -c tmenu.c -I$(INCL)
ticmp: ticmp.o
	gcc -o ticmp ticmp.o -L$(LIBPATH) $(LIBS)
ticmp.o: ticmp.c
	gcc -c ticmp.c -I$(INCL)
tscan: tscan.o
	gcc -o tscan tscan.o -L$(LIBPATH) $(LIBS)
tscan.o: tscan.c
	gcc -c tscan.c -I$(INCL)
tcplog: tcplog.o
	gcc -o tcplog tcplog.o -L$(LIBPATH) $(LIBS)
tcplog.o: tcplog.c
	gcc -c tcplog.c -I$(INCL)
solicit: solicit.o
	gcc -o solicit solicit.o -L$(LIBPATH) $(LIBS)
solicit.o: solicit.c
	gcc -c solicit.c -I$(INCL)
re1: re1.o
	gcc -o re1 re1.o -L$(LIBPATH) $(LIBS)
re1.o: re1.c
	gcc -c re1.c -I$(INCL)
dh1: dh1.o
	gcc -o dh1 dh1.o -L$(LIBPATH) $(LIBS)
dh1.o: dh1.c
	gcc -c dh1.c -I$(INCL)
pmtu: pmtu.o
	gcc -o pmtu pmtu.o -L$(LIBPATH) $(LIBS)
pmtu.o: pmtu.c
	gcc -c pmtu.c -I$(INCL)
~tscan: ~tscan.o
	gcc -o ~tscan ~tscan.o -L$(LIBPATH) $(LIBS)
~tscan.o: ~tscan.c
	gcc -c ~tscan.c -I$(INCL)
tell: tell.o
	gcc -o tell tell.o -L$(LIBPATH) $(LIBS)
tell.o: tell.c
	gcc -c tell.c -I$(INCL)
dynaip: dynaip.o
	gcc -o dynaip dynaip.o -L$(LIBPATH) $(LIBS)
dynaip.o: dynaip.c
	gcc -c dynaip.c -I$(INCL)
whohas: whohas.o
	gcc -o whohas whohas.o -L$(LIBPATH) $(LIBS)
whohas.o: whohas.c
	gcc -c whohas.c -I$(INCL)
tserv: tserv.o
	gcc -o tserv tserv.o -L$(LIBPATH) $(LIBS)
tserv.o: tserv.c
	gcc -c tserv.c -I$(INCL)
bridge: bridge.o
	gcc -o bridge bridge.o -L$(LIBPATH) $(LIBS)
bridge.o: bridge.c
	gcc -c bridge.c -I$(INCL)
dltype: dltype.o
	gcc -o dltype dltype.o -L$(LIBPATH) $(LIBS)
dltype.o: dltype.c
	gcc -c dltype.c -I$(INCL)
icmask: icmask.o
	gcc -o icmask icmask.o -L$(LIBPATH) $(LIBS)
icmask.o: icmask.c
	gcc -c icmask.c -I$(INCL)
rtest: rtest.o
	gcc -o rtest rtest.o -L$(LIBPATH) $(LIBS)
rtest.o: rtest.c
	gcc -c rtest.c -I$(INCL)
honeyport: honeyport.o
	gcc -o honeyport honeyport.o -L$(LIBPATH) $(LIBS)
honeyport.o: honeyport.c
	gcc -c honeyport.c -I$(INCL)
seq: seq.o
	gcc -o seq seq.o -L$(LIBPATH) $(LIBS)
seq.o: seq.c
	gcc -c seq.c -I$(INCL)
sniffer: sniffer.o
	gcc -o sniffer sniffer.o -L$(LIBPATH) $(LIBS)
sniffer.o: sniffer.c
	gcc -c sniffer.c -I$(INCL)
readcap: readcap.o
	gcc -o readcap readcap.o -L$(LIBPATH) $(LIBS)
readcap.o: readcap.c
	gcc -c readcap.c -I$(INCL)
trst: trst.o
	gcc -o trst trst.o -L$(LIBPATH) $(LIBS)
trst.o: trst.c
	gcc -c trst.c -I$(INCL)
crmk: crmk.o
	gcc -o crmk crmk.o -L$(LIBPATH) $(LIBS)
crmk.o: crmk.c
	gcc -c crmk.c -I$(INCL)
prncap: prncap.o
	gcc -o prncap prncap.o -L$(LIBPATH) $(LIBS)
prncap.o: prncap.c
	gcc -c prncap.c -I$(INCL)
arp_reply: arp_reply.o
	gcc -o arp_reply arp_reply.o -L$(LIBPATH) $(LIBS)
arp_reply.o: arp_reply.c
	gcc -c arp_reply.c -I$(INCL)
send_syn: send_syn.o
	gcc -o send_syn send_syn.o -L$(LIBPATH) $(LIBS)
send_syn.o: send_syn.c
	gcc -c send_syn.c -I$(INCL)
syn_trace: syn_trace.o
	gcc -o syn_trace syn_trace.o -L$(LIBPATH) $(LIBS)
syn_trace.o: syn_trace.c
	gcc -c syn_trace.c -I$(INCL)
client_pscan: client_pscan.o
	gcc -o client_pscan client_pscan.o -L$(LIBPATH) $(LIBS)
client_pscan.o: client_pscan.c
	gcc -c client_pscan.c -I$(INCL)
cli_scan: cli_scan.o
	gcc -o cli_scan cli_scan.o -L$(LIBPATH) $(LIBS)
cli_scan.o: cli_scan.c
	gcc -c cli_scan.c -I$(INCL)
tcp_rst: tcp_rst.o
	gcc -o tcp_rst tcp_rst.o -L$(LIBPATH) $(LIBS)
tcp_rst.o: tcp_rst.c
	gcc -c tcp_rst.c -I$(INCL)
cli_scan_lan: cli_scan_lan.o
	gcc -o cli_scan_lan cli_scan_lan.o -L$(LIBPATH) $(LIBS)
cli_scan_lan.o: cli_scan_lan.c
	gcc -c cli_scan_lan.c -I$(INCL)
synack: synack.o
	gcc -o synack synack.o -L$(LIBPATH) $(LIBS)
synack.o: synack.c
	gcc -c synack.c -I$(INCL)
synack_lan: synack_lan.o
	gcc -o synack_lan synack_lan.o -L$(LIBPATH) $(LIBS)
synack_lan.o: synack_lan.c
	gcc -c synack_lan.c -I$(INCL)
sizeoflong: sizeoflong.o
	gcc -o sizeoflong sizeoflong.o -L$(LIBPATH) $(LIBS)
sizeoflong.o: sizeoflong.c
	gcc -c sizeoflong.c -I$(INCL)
sq: sq.o
	gcc -o sq sq.o -L$(LIBPATH) $(LIBS)
sq.o: sq.c
	gcc -c sq.c -I$(INCL)
